# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Assist Tutorials
email: prar@hawaii.edu
description: Assist makes your life easier.
pathname: "" # the subpath of your site, e.g. /blog
hostname: "https://assist.coe.hawaii.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# Number of posts displayed, before paginated
paginate: 8
paginate_path: "/page:num/"
exclude: [node_modules, gulpfile.js, package.json, README.md, .gitignore, .travis.yml, Gemfile, scripts, vendor]

# Gems
gems:
- jekyll-paginate





